### ISSUE TITLE
Incomplete reconnect after server restart

### ISSUE THREAD

**Issue by m-ober** [JensForstmann/tmt2#18]
After a hard restart of the Gameserver, TMT2 reconnets but is unable to receive any messages. See the attached screenshot:

![tmt2_message_after_hard_restart_server](https://user-images.githubusercontent.com/11992838/184026058-964c4aad-3668-4cb3-a233-ac89ea3a3224.png)

**Comment by JensForstmann** [comment]
I always start my game servers with `+log on` so this one slipped through.

Should be fixed now.
