### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Miraculix1337** [JensForstmann/tmt2#23]
Hi Its me again xD,

is it possible to add more information on the Match site? When i click on the Match tab in tmt i can see a lot of Matches, the problem is i dont know on which server they are running. So it woul be ok for me when the ip adress would be shown in the Match overwview tab.

Is this Possible?

Regards Tobi

**Comment by JensForstmann** [comment]
Great idea! It's implemented, together with a menu to configure the shown columns.
