### ISSUE TITLE
No Player reset with looped match

### ISSUE THREAD

**Issue by Miraculix1337** [JensForstmann/tmt2#24]
Hi,

i saw a bug at our LAN. When i set up the Matches in Loop mode there will be a lot of players in the Teams. See the picture.

![Screenshot 2023-10-29 013445](https://github.com/JensForstmann/tmt2/assets/42931805/cab5cd42-4b92-444d-9c88-56d218fc4f62)

Regards
Tobi

**Comment by JensForstmann** [comment]
Yeah, probably a good idea to empty the player list!

Implemented in 679ef084a05a02c6227627b9778aacf17f49597e
