### ISSUE TITLE
No Match Backup with Looped Matches

### ISSUE THREAD

**Issue by Miraculix1337** [JensForstmann/tmt2#25]
Hi,

it is not possible to restore a Match when it is in Loop Modus. Afte a lot of played rounds TMT seems not to save the backups any more.

I also had a strange behavior at the finals at 2v2 and 5v5. I set up the team Names and also the score for the winner bracket team. After the electionphase / Knive the server crashed. I know that the server is crap atm but i wanted to keep you aware of this problem.

Regards
Tobi

**Comment by JensForstmann** [comment]
I tested it with competitive settings and played over 200 rounds in total. Depending on which map the server currently was I always got the latest round backups and could restore them.

Without any hints how to reproduce it I cannot do anything.

Short note at this point: TMT has no own system for round backups, it just uses the official one from the CS2 server. If the game server is losing the round backups file (e.g. server in container without data persistance), TMT can't do anything.

Here are the corresponding RCON commands: https://github.com/JensForstmann/tmt2/blob/main/backend/src/match.ts#L191-L197
