### ISSUE TITLE
Add .tac for a tactical timeout

### ISSUE THREAD

**Issue by bonkersGER** [JensForstmann/tmt2#31]
Would be nice to have a command like .tac for a tactical timeout

**Comment by JensForstmann** [comment]
Would a tactical timeout be different from the `.pause`?

**Comment by bonkersGER** [comment]
You can define how many pauses a team can use per match 

mp_team_timeout_max 4
mp_team_timeout_time 30

**Comment by bonkersGER** [comment]
The server admin or the leauge referee can force the pausing commands via rcon or console

Counter-terrorist Team
 timeout_ct_start 
Terrorist Team
 timeout_terrorist_start

**Comment by JensForstmann** [comment]
What benefits do you see with `.tac` in comparision to the normal way of starting a tactical timeout?

![image](https://github.com/JensForstmann/tmt2/assets/19289807/53eee617-96a7-43ba-911f-0963365a08fe)

**Comment by bonkersGER** [comment]
The user does all interactions with simple chat commands but for a tactical timeout he has to use the the ingame menu. It is just a small consistency upgrade :)

**Comment by JensForstmann** [comment]
Okay, currently TMT2 offers only commands for things the players cannot do on their own. But I think it's okay to have another way to pause the match for tactical or technical reasons 👍

**Comment by JensForstmann** [comment]
![image](https://github.com/JensForstmann/tmt2/assets/19289807/510bac86-9e0d-43ba-8a92-6cdc8df45ed5)


There it is!
