### ISSUE TITLE
game mode in the match overview

### ISSUE THREAD

**Issue by Egosar93** [JensForstmann/tmt2#35]
Hey, can you also add the game mode in the match overview. So 2on2 or 5on5?

**Comment by JensForstmann** [comment]
Do you mean on the detail page of one match? Or on the overview page with all matches in the table?

Not sure how to approach this in a good way. TMT doesn't know the concept of a 2on2/5on5. It knows the players which are online on the server (or have been in the past). So an extra column with player counts is possible. But that doesn't help if no player has connected, yet.

**Comment by JensForstmann** [comment]
95d47a2fada56defdc210555ef8c75ae53919c3d

![image](https://github.com/JensForstmann/tmt2/assets/19289807/124066b7-f766-4f24-90ca-902ea9444b85)
